name: Build Docker Image

on:
  push:
    branches: [ "main" ]
    pull_request: [ "main" ]

jobs:
  compile:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '^1.13.1'
    - name: Compile project
      run: cd docker && make compile

  build:
    needs: compile
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: cd docker && make build
