name: Lint

on:
  # Replace pull_request with pull_request_target if you
  # plan to use this action with forks, see the Limitations section
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions: {}

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    permissions:
          contents: read
          pull-requests: read
          packages: read
          checks: write
          # To report GitHub Actions status checks
          statuses: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60

      # SUPER LINTER
      # - name: Checkout code
      #   uses: actions/checkout@v4
      #   with:
      #     # super-linter needs the full git history to get the
      #     # list of files that changed across commits
      #     fetch-depth: 0
      #
      # - name: Super-linter
      #   uses: super-linter/super-linter@v7.1.0 # x-release-please-version
      #   env:
      #     # To report GitHub Actions status checks
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     DISABLE_ERRORS: true
      #     SAVE_SUPER_LINTER_OUTPUT: true

      # - run: ls -l
      #
      # - name: Annotate
      #   uses: yuzutech/annotations-action@v0.4.0
      #   with:
      #     repo-token: "${{ secrets.GITHUB_TOKEN }}"
      #     title: 'lint'
      #     input: './super-linter-output'
